### ISSUE TITLE
Memory leak bug because of unmounted Loading button

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#228]
Because our modals unmount before the Loading button completes its state update, we receive the memory leak error message shown below:

<img width="1792" alt="Screenshot 2020-11-13 at 10 25 10 AM" src="https://user-images.githubusercontent.com/39231249/99056373-831f7400-259a-11eb-9b23-6f22d078f21d.png">

This happens for all modals (mediaModal, hyperlinkModal etc) that close once the Loading button is clicked because of the following lines in the `LoadingButton.jsx` component [link](https://github.com/isomerpages/isomercms-frontend/blob/467adeb593dd5fcbc6c4a1cb609c38f03015c78f/src/components/LoadingButton.jsx#L22):

```
      onClick={async () => {
        setButtonLoading(true);
        await callback();
        setButtonLoading(false);
      }}
```

**Comment by kwajiehao** [comment]
So it turns out that the issue isn't to do with the lines specified:

```
      onClick={async () => {
        setButtonLoading(true);
        await callback();
        setButtonLoading(false);
      }}
```

but from the fact that we are attempting to set the button loading state to `false` even after the `LoadingButton` component has unmounted (because the modal has closed). The fix is to add a condition to update state only when the component is mounted (reference: https://stackoverflow.com/questions/53949393/cant-perform-a-react-state-update-on-an-unmounted-component)
