### ISSUE TITLE
Pull request button

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#382]
This pull request button leads user to their pull request page when they are ready to publish the changes from staging to production

**Comment by sarahsalim** [comment]
![Workspace](https://user-images.githubusercontent.com/27407507/112575293-04c9bd00-8e2b-11eb-9599-259cea03c32f.png)

As discussed, Pull request button -> Github page -> Pull Request Tab

**Comment by sarahsalim** [comment]
Updated the side nav bar with an additional button 'Guide' to link users directly to the guide. 

Our guide is comprehensive, but currently a little hidden. This button hopes to improve accessibility and discovery of the guide itself, but also to encourage and empower users to self-help so that they can grow to become power users more independently and rely less on user support in future :)

![Workspace](https://user-images.githubusercontent.com/27407507/113083638-1d611b00-920f-11eb-9c87-b321b665a715.png)
