### ISSUE TITLE
All components that retrieve data via API should redirect to `/not-found` if they experience a 404 error

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-frontend#434]
To-do: identify these components

kat: can be combined with #339 ?

**Comment by kwajiehao** [comment]
I agree that we should restrict the route selector's job to simply routing. The reason why we had this check in `ProtectedRoute` is because this check applies for all repo-specific layouts (basically all the layouts except for `Sites` and `Home`) instead of implementing them one by one. Perhaps we can create another higher-order component which renders all site-specific layouts as children while also running this useEffect check? So

```
<RouteSelector>
  <Home />
  <Sites />
  <HOC>
    < ... all site-specific layouts>
  </ HOC>
</RouteSelector>
```

**Comment by prestonlimlianjie** [comment]
Related to https://github.com/isomerpages/isomercms-frontend/issues/339

**Comment by kathleenkhy** [comment]
to be done with #339
