### ISSUE TITLE
'Rearrange items' on cms not working

### ISSUE THREAD

**Issue by jacksonOGP** [isomerpages/isomercms-frontend#545]
**Describe the bug**
After user make the changes to how the pages are displayed on navigation bar with 'Rearrange items' on CMS, the change do not reflect on the staging site.

Verified on github collection.yml 

**To Reproduce**
1. Go to any cms collection
2. Click on 'Rearrange item'
3. Arrange
4. Go to staging site

**Expected behavior**
The arrange items should show on staging site

**Screenshots**

![intended](https://user-images.githubusercontent.com/70509050/126111809-4da070d7-5203-4021-a902-982a3e666873.png)

![unexpected buggy](https://user-images.githubusercontent.com/70509050/126112416-63028423-f610-4a1f-a244-cc6431d79356.png)

![collection.yml](https://user-images.githubusercontent.com/70509050/126112803-732826b7-3099-49d7-95fb-a93e970682fa.png)

Affected repo and collection
https://github.com/isomerpages/nlb-IOHA2020

**Comment by gweiying** [comment]
Related to repo misconfig: IOHA was supposed to be using the new Gemfile with `isomer-jekyll` but was using the prev `github-pages` because it was accidentally overridden. Issue discovered and resolved by @prestonlimlianjie 

Verified that it's working now. <img width="428" alt="Screenshot 2021-08-10 at 9 43 00 AM" src="https://user-images.githubusercontent.com/39231249/128795594-d6c90155-1728-4d38-ab9d-eeb7ced45ec4.png">
