### ISSUE TITLE
Fixes for 31-March-2022 Release

### ISSUE THREAD

**Issue by rc-davis** [isomerpages/isomercms-frontend#826]
Must Fix
- [x] when clicking reply all to email OTP, should show noreply@isomer.gov.sg instead of kee wei’s email (@alexanderleegs)
- [x] ping fix should resolve env health issue (@alexanderleegs )
- [x] remove cookie from being logged to prevent false errors from being captured (@seaerchin)
- [x] ~Check that we're not sending too many alerts (@alexanderleegs )~ We're being alerted if email/sms fails to send, which we do want to know

KIV

Defer (tackle next week)
- [x] https://github.com/isomerpages/isomercms-backend/issues/409

**Comment by prestonlimlianjie** [comment]
The issue `change SMS sender id from Postman to Isomer OTP (works as expected on test sms from postman but when using transactional api, doesn’t work)` appears to be a Postman transactional SMS API limitation.

The API only exposes `body`, `recipient`, and `label`, but no configuration for the sender name. In order to overcome this, we should make a direct API call to Twilio instead.

At this moment, Postman does not provide significant benefit for sending SMSes, and so we could do without this middle-post-man

**Comment by seaerchin** [comment]
> The issue `change SMS sender id from Postman to Isomer OTP (works as expected on test sms from postman but when using transactional api, doesn’t work)` appears to be a Postman transactional SMS API limitation.
> 
> The API only exposes `body`, `recipient`, and `label`, but no configuration for the sender name. In order to overcome this, we should make a direct API call to Twilio instead.
> 
> At this moment, Postman does not provide significant benefit for sending SMSes, and so we could do without this middle-post-man
> 
> Created a new issue: Created a new issue: [isomerpages/isomercms-backend#409](https://github.com/isomerpages/isomercms-backend/issues/409). Let's tackle this next week.

great pun btw
